//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelibsClientTCP.VelibsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibsService.IVelibsOptimisation")]
    public interface IVelibsOptimisation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsOptimisation/GetDirections", ReplyAction="http://tempuri.org/IVelibsOptimisation/GetDirectionsResponse")]
        string[] GetDirections(string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsOptimisation/GetDirections", ReplyAction="http://tempuri.org/IVelibsOptimisation/GetDirectionsResponse")]
        System.Threading.Tasks.Task<string[]> GetDirectionsAsync(string origin, string destination);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibsOptimisationChannel : VelibsClientTCP.VelibsService.IVelibsOptimisation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibsOptimisationClient : System.ServiceModel.ClientBase<VelibsClientTCP.VelibsService.IVelibsOptimisation>, VelibsClientTCP.VelibsService.IVelibsOptimisation {
        
        public VelibsOptimisationClient() {
        }
        
        public VelibsOptimisationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibsOptimisationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibsOptimisationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibsOptimisationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetDirections(string origin, string destination) {
            return base.Channel.GetDirections(origin, destination);
        }
        
        public System.Threading.Tasks.Task<string[]> GetDirectionsAsync(string origin, string destination) {
            return base.Channel.GetDirectionsAsync(origin, destination);
        }
    }
}
